Feature/jc19 352 initialize anime app and table view
saritasa-nest/camp-js-2022-loc-tran pull request #1
Opened 2022-07-07 06:17 UTC by LocTran-saritasa

Initialize Anime app and table view with Vanilla JS/HTML/CSS

2022-07-07 07:56 UTC, TienLuu-Saritasa commented on apps/vanilla/src/pages/index.css
> +table th td {
```suggestion
.table th td {
```

2022-07-07 07:59 UTC, TienLuu-Saritasa commented on apps/vanilla/src/pages/index.css
> +#sort,
https://wiki.saritasa.rocks/frontend/languages/html#avoid-id

2022-07-07 08:01 UTC, TienLuu-Saritasa commented on apps/vanilla/src/pages/index.html
> +    <div class="title">Anime table</div>
Should we use `h1` tag for title?

2022-07-07 08:07 UTC, TienLuu-Saritasa commented on libs/core/dtos/anime.dto.ts
> +interface AiredDto {
You could create `DateRange` and type with it everything related to `start` and `end` dates

2022-07-07 08:09 UTC, TienLuu-Saritasa commented on libs/core/dtos/anime.dto.ts
> +interface AiredDto {
```
/** Period of time. */
export interface DateRange {

  /** Start of the period. */
  readonly start: Date;

  /** End of the period. */
  readonly end: Date;
}

```

2022-07-07 08:26 UTC, timofei-maximov-saritasa requested changes

2022-07-07 08:26 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/script/generateUrl.ts
> +  ordering = localStorage.getItem('ANIME_ORDER') ?? ''): string {
You have many arguments in this function. You passing `queryOptions`. Let's replace your function arguments with an object. It will be easier and safer, since ide won't help you with right argument order. And also you can reuse interface for other queries.

```ts
interface QueryOptions {
  readonly offset: string; // use `?` if you want to make it optional.
  readonly limit: number;
  // and so on.
}

2022-07-07 08:26 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/script/handleChange.ts
> +  if (count) {
Please, don't use [implicit type-casting](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#dont-use-implicit-type-casting)

2022-07-07 08:26 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/script/handleChange.ts
> +  updateAnime(generateUrl(undefined, undefined, sortOption));
Using object as an argument will help you here)

2022-07-07 08:26 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/script/renderToDOM.ts
> +  if (tableRow) {
Same about implicit type-casting

2022-07-07 08:26 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/script/renderToDOM.ts
> +    for (let i = first; i <= first + 6 && i <= Math.ceil(count / LIMIT); i++) {
Please, don't use magic values. Right now it is not obvious what is `6`

2022-07-07 08:26 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/script/renderToDOM.ts
> +  const button = document.createElement('div');
Why is your `button` is `div`? Let's improve accessibility by using `button` element instead of `div`.

2022-07-07 08:26 UTC, timofei-maximov-saritasa commented on libs/core/mappers/anime.mapper.ts
> +export namespace animeMapper {
```suggestion
export namespace AnimeMapper {
```

2022-07-07 08:34 UTC, TienLuu-Saritasa requested changes

2022-07-07 08:34 UTC, TienLuu-Saritasa commented on apps/vanilla/src/script/constants.ts
> + * Enum for sorting.
Prefer one-line jsdocs `/** Enum for sorting. */`

2022-07-07 08:34 UTC, TienLuu-Saritasa commented on apps/vanilla/src/script/generateUrl.ts
> +  if (!offset) {
https://wiki.saritasa.rocks/frontend/practices/code#be-explicit
I think it should be `offset !== 0`, right?

2022-07-07 08:34 UTC, TienLuu-Saritasa commented on apps/vanilla/src/script/handleChange.ts
> +  if (!(data instanceof Error)) {
Same as above

2022-07-07 13:01 UTC, gevorg-gevorgyan-saritasa requested changes

2022-07-07 13:01 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/script/init.ts
> +  const firstPageButton = document.querySelector('#first-page-button');
Try to replace id with class if it's possible, please. https://wiki.saritasa.rocks/frontend/languages/html#avoid-id

2022-07-07 13:25 UTC, TienLuu-Saritasa commented on apps/vanilla/src/pages/index.css
> +.pagination__button.active {
Please stick to [BEM](https://wiki.saritasa.rocks/frontend/languages/css#bem)
```suggestion
.pagination__button_active
```

2022-07-07 13:33 UTC, TienLuu-Saritasa commented on apps/vanilla/src/pages/index.css
> +  font-size: 1rem;
Default font size is 1rem, is there any reason to use it here?

2022-07-07 13:37 UTC, TienLuu-Saritasa commented on apps/vanilla/src/script/fetchAnime.ts
> +    return paginationMapper.fromDto(paginationData);
```suggestion
    return paginationMapper.fromDto(response.data);
```

2022-07-07 13:42 UTC, TienLuu-Saritasa commented on libs/core/dtos/anime.dto.ts
> +/** Aired DTO. */
Please update your jsdoc and move `DateRange`  into a separate file. It does not relate to `anime`

2022-07-07 13:44 UTC, TienLuu-Saritasa commented on libs/core/models/anime.ts
> +  readonly start: string;
Are you sure it is a `string`? Also, please reuse your `DateRange`

2022-07-07 13:59 UTC, timofei-maximov-saritasa commented on package.json
> +    "dotenv": "^16.0.1",
https://github.com/saritasa-nest/camp-js-2022-dao-duong/pull/1#discussion_r915906238

2022-07-07 14:11 UTC, TienLuu-Saritasa commented on apps/vanilla/src/global/variables.css
> +  --heading-color-1: #1229a7;
> Please group them, use empty line and/or comments.

2022-07-08 03:40 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/index.css
> +  font-size: 1rem;
For some reason, the default font size of that element is 13.3333px so I have to style it 1rem.

2022-07-08 06:25 UTC, golovachev-yaroslav requested changes

2022-07-08 06:25 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.css
> +  font-family: Arial, Helvetica, sans-serif;
As I know, the Arial font is available only for Windows platform. Could you check please. Also it would be better to use CSS var for `Arial, Helvetica, sans-serif;`

2022-07-08 06:25 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.html
> +      <button class="pagination__button first-page-button">first</button>
Don't forget to add `type="button"`

2022-07-08 06:51 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/index.css
> +  font-family: Arial, Helvetica, sans-serif;
> Arial and members of the Arial font family are considered the safest web fonts because they’re available on all major operating systems.

I found it at [https://blog.hubspot.com/website/web-safe-html-css-fonts](url)
So I think it's still available for other OS

2022-07-08 08:55 UTC, artem-sotnichenko-saritasa requested changes

2022-07-08 08:55 UTC, artem-sotnichenko-saritasa commented on libs/core/mappers/anime.mapper.ts
> +    return anime;
You don't really need to create variable here.
```suggestion
    return {
      id: dto.id,
      titleEnglish: dto.title_eng,
      titleJapan: dto.title_jpn,
      image: dto.image,
      aired: DateRangeMapper.fromDto(dto.aired),
      type: dto.type,
      status: dto.status,
    };
```

2022-07-08 08:55 UTC, artem-sotnichenko-saritasa commented on libs/core/mappers/anime.mapper.ts
> +    return anime;
And in other mappers too

2022-07-09 10:27 UTC, golovachev-yaroslav approved these changes

2022-07-11 09:10 UTC, panov-aleksey-saritasa commented on libs/core/models/query.ts
> +  readonly ordering: string;
From the docs it's not clear how what's the difference between `sorting` and `ordering` 🤔

2022-07-11 09:10 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/script/fetchAnime.ts
> +  }
If an error is not business-related, consider delegating error handling to function consumers instead.
Also prefer propagating errors via `throw` rather than returning them

2022-07-11 09:10 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/script/generateUrl.ts
> +  return `${import.meta.env.VITE_API_URL}/api/v1/anime/anime/?limit=${limit}&offset=${offset}&ordering=${ordering}${sorting ?? ''}`;
Consider making a constant out of `import.meta.env.VITE_API_URL`
I am sure you are going to use it for other requests

2022-07-11 09:10 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/script/constants.ts
> +  },
Have you fixed this? 🤔

2022-07-11 15:02 UTC, LocTran-saritasa commented on apps/vanilla/src/pages/index.css
> +  max-height: 200px;
Yes, I always prefer to use flexible approach so I  used max-width and max-height in the mentioned code.

2022-07-11 15:19 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/script/generateUrl.ts
> +export function generateUrl(query: Query): string {
The function is used to generate the url request. But it looks not generally. 
It is using to generate for anime only.

2022-07-11 15:19 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/script/generateUrl.ts
> +  return `${API_URL}/api/v1/anime/anime/?limit=${limit}&offset=${offset}&ordering=${ordering}${sorting ?? ''}`;
Please help me understand why we need API_URL here, even we already config in the axios instance 'http'

2022-07-11 15:19 UTC, thanhnguyen-saritasa commented on libs/core/models/query.ts
> +  readonly sorting: string;
Please check API doc about the "ordering" param.
Example: https://api.camp-js.saritasa.rocks/api/v1/open-api/ui/#/anime/anime_anime_list
I do not see we need to have this parameter.

2022-07-12 02:10 UTC, LocTran-saritasa commented on libs/core/models/query.ts
> +  readonly sorting: string;
I have both sorting and ordering parameters. Sorting specifies the sort type like title_eng, title_jap, ... While ordering specifies the order of list is Descending or Ascending. Look like the naming is not good so I will change ordering parameter to orderType.

2022-07-12 11:19 UTC, thanhnguyen-saritasa commented on libs/core/models/query.ts
> +  readonly nullValue: string;
Please help me understand why we need it, tks

2022-07-12 11:19 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/script/generateUrl.ts
> +export function generateUrl(url: string, queries: Queries): string {
It looks complicated logic in the function.
Could we implement the function to understand with its name. 
It just generate the request Url with query parameters.
Let thinking about in case we want to have the URL without logic get query value from localStorage.
BTW, getting any data from localStorage could separate to another service, example: storageService.

2022-07-12 11:19 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/script/generateUrl.ts
> +export function generateUrl(url: string, queries: Queries): string {
We can use 'params' as axios documentation.
https://github.com/axios/axios#note-commonjs-usage

2022-07-13 02:46 UTC, LocTran-saritasa commented on libs/core/models/query.ts
> +  readonly nullValue: string;
The way I use my Query interface is: 
if value = null value (not assigned) -> find in local storage -> if not found in local storage -> use null value as default value for query
Because each query has a different default value so I must store its default value into interface Query. 
It seems the naming is not suitable so let me change it to defaultValue

2022-07-13 03:35 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-07-13 05:25 UTC, thanhnguyen-saritasa approved these changes

2022-07-13 16:30 UTC, chernodub requested changes

2022-07-13 16:30 UTC, chernodub commented on apps/vanilla/src/script/init.ts
> +      tableRow.append(row);
It is very strange that you insert a row into another row, this seems like invalid HTML. [TR can not be nested into another TR](https://caninclude.glitch.me/caninclude?child=tr&parent=tr)

2022-07-14 03:45 UTC, LocTran-saritasa commented on apps/vanilla/src/script/init.ts
> +      tableRow.append(row);
It 's my mistake in naming. Instead of "row", it should be "cell".

2022-07-15 02:56 UTC, pavel-romanov8 requested changes

2022-07-15 02:56 UTC, pavel-romanov8 commented on apps/vanilla/src/global/variables.css
> +  /* you shouldn't be using color names in real projects. */
Please, omit this comment

2022-07-15 02:56 UTC, pavel-romanov8 commented on apps/vanilla/src/namespaces/PageHandler.ts
> +  export function goToPageByNum(newPage: number): void {
The documentation and method name absolutely different, therefore none of them are accurate. Either update method documentation or rename the method

2022-07-15 02:56 UTC, pavel-romanov8 commented on apps/vanilla/src/namespaces/PageHandler.ts
> +    localStorage.setItem(OFFSET_LS, (LIMIT * (newPage - 1)).toString());
It is really not a good thing to store the pagination values in `localStorage` because it is leading to bad UX when user visit your main page, but have some pagination data that will be user right away. Instead, prefer using search params (query params) to do such things. Some big tech (Amazon, Alibaba, etc.) companies also using such approach to handle the pagination. You can visit their sites and check the example

2022-07-15 02:56 UTC, pavel-romanov8 commented on apps/vanilla/src/namespaces/PageHandler.ts
> +          generateQuery(SORT_HEADER, DEFAULT_SORTING, SORT_LS, DEFAULT_SORTING),
I see that you are basically duplicating the last 2 queries from `goToPageByNum ` and here. Also, each of them are not depends on any of the function variables, arguments, so I suggest you to move it outside the functions

2022-07-15 02:56 UTC, pavel-romanov8 commented on apps/vanilla/src/namespaces/PageHandler.ts
> +      const page = Math.ceil(Number.parseInt(count, DECIMAL) / LIMIT);
The `Number.parseInt` might return `NaN` as well. Please, consider handling this case

2022-07-15 02:56 UTC, pavel-romanov8 commented on apps/vanilla/src/script/constants.ts
> +  AiredStart = 'aired__startswith',
Please, do not use BE values directly to perform some actions. We should have 2 different sorting enums 1 for DTO values which stand for values, that BE is sending to us and other one is our sorting enum which we will use in our app. That way we are not coupling ourselves to some specific BE implementation and there will be minimum places to change in order we decide to change the API

2022-07-15 02:56 UTC, pavel-romanov8 commented on apps/vanilla/src/script/constants.ts
> +      localStorageName: OFFSET_LS,
Please, do not expose the `locaStorage` abstraction outside some bound where it should be used. Here we are operating with `queries` only, but why should we know something about `localStorage`?

2022-07-15 02:56 UTC, pavel-romanov8 commented on apps/vanilla/src/script/helpers.ts
> +export function generateQuery(name: string, value: string | number, localStorageName: string, defaultValue = ''): Query {
The same thing about `localStorage` abstraction

2022-07-15 02:56 UTC, pavel-romanov8 commented on apps/vanilla/src/services/localStorage.ts
> +export function findInLocalStorage(value: string, localStorageName: string): string {
We have too many places where we are trying to access `localStorage`, but we shouldn't do so, because abstraction of `storage` leaking all over the app and will bring a lot of mess. As i already suggested you, we should consider changing pagination location from `localStorage` to search params, but let me give you a brief explanation about why it is not a really good thing to have so widely accessible thing as `localStorage`.

If we have 1 uncontrolled access to the source of truth, that means that anyone from anywhere can change it, and you can't be 100% sure that the data is accurate. You have to validate it every time in order to be sure that it is indeed valid, but it is really not possible in some cases and your app might be just broken because of stale or irrelevant data

2022-07-15 02:56 UTC, pavel-romanov8 commented on libs/core/dtos/anime.dto.ts
> +export enum AnimeStatus {
We are using the same field in our model and DTO which is really not a good practice. Consider mapping them, as i already suggested for the `Sorting` enum

2022-07-15 02:56 UTC, pavel-romanov8 commented on libs/core/dtos/anime.dto.ts
> +  music = 'MUSIC',
Usually we name fields in our enum in `PascalCase` like we do for their names

2022-07-15 02:56 UTC, pavel-romanov8 commented on libs/core/models/anime.ts
> +  /** Japan title of the anime. */
```suggestion
  /** Japanese title of the anime. */
```

2022-07-15 02:56 UTC, pavel-romanov8 commented on libs/core/models/dateRange.ts
> +  /** End date Anime. */
The name of model doesn't refer us to `anime` somehow, but in the docs we do so. Let'e either improve the naming or docs in order to match them

2022-07-15 02:56 UTC, pavel-romanov8 commented on libs/core/models/option.ts
> +
Redundant empty line

2022-07-15 04:27 UTC, TienLuu-Saritasa approved these changes

2022-07-15 04:42 UTC, LocTran-saritasa commented on apps/vanilla/src/namespaces/PageHandler.ts
> +    localStorage.setItem(OFFSET_LS, (LIMIT * (newPage - 1)).toString());
Thank you very much. Let me remove the pagination values in `localStorage`. But I have some explanations for why I did it.
Because I prefer the behavior that:
**User choose page 5 -> Move to page 5 -> User choose sort by Title -> User at _page 5_ of the list are sorted by Title**
So I must store page 5 for next request. If I don't store pagination values in local storage I can't implement that because as I know that in vanilla there are not any global states like some frameworks, all variable values ​​will be released after the function is done executing.
So I'll change it to
**User choose page 5 -> Move to page 5 -> User choose sort by Title -> User at _default page_ of the list are sorted by Title**

2022-07-15 06:51 UTC, LocTran-saritasa commented on apps/vanilla/src/namespaces/PageHandler.ts
> +    localStorage.setItem(OFFSET_LS, (LIMIT * (newPage - 1)).toString());
I prefer using search params to store the pagination values and other query values like sort and filter too. But I in vanilla JS, to config the URL for search params is quite difficult.
I can remove the pagination values from `localStorage` but whenever user change the sort option or filter option, the page will set to default page is page 1. Is it fine? :sweat_smile:

2022-07-15 07:00 UTC, pavel-romanov8 commented on apps/vanilla/src/namespaces/PageHandler.ts
> +    localStorage.setItem(OFFSET_LS, (LIMIT * (newPage - 1)).toString());
I believe that it is the behaviour that users expects, because it is strange to see the 3rd page of filtered results instead of the first one

2022-07-18 18:00 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/script/constants.ts
> +import { OrderOption, SortOption } from '@js-camp/core/models/option';
collecting all constants in one file, mixing UI and API is a bad idea, put these constants next to the methods that use them, this approach will be more maintainable.

2022-07-18 18:31 UTC, pavelzadorin-saritasa requested changes

2022-07-18 18:31 UTC, pavelzadorin-saritasa commented on libs/core/mappers/anime.mapper.ts
> +    const status = animeStatusDtoToModel[dto.status] !== undefined ? animeStatusDtoToModel[dto.status] : AnimeStatus.Airing;
implicit setting defaults are prone to errors, for example why did we decide that the default type should be TV?
I suggest to do the following, check if there are values in the database where Type or Status is empty? For example, let's sort by status in different orders, and we will see that there is no Anime with an empty status (I think the same with the type), which means we don't need to handle the case of an empty status in a special way, it will be enough, for example, to report to the console and skip this anime or throw an exception.

2022-07-18 18:31 UTC, pavelzadorin-saritasa commented on libs/core/models/option.ts
> +export interface OrderOption {
these interfaces are identical, I think you can make one `SelectionOption` interface and use it for both cases.

2022-07-21 03:10 UTC, maxineo approved these changes

2022-07-25 06:43 UTC, pavelzadorin-saritasa approved these changes

2022-07-28 04:56 UTC, chernodub approved these changes

2022-07-28 04:56 UTC, chernodub commented on apps/vanilla/src/namespaces/PageHandler.ts
> +  export function goToPageByNum(newPage: number): void {
@LocTran-saritasa seems like this comment is resolved without a code fix. _If you received a comment with which you do not agree, you must not resolve it silently. Answer it, and make sure the person who left the comment agreed with you (or vice-versa). Only then a comment may be considered as resolved._ [link](https://wiki.saritasa.rocks/general/git#code-review)

2022-07-28 04:56 UTC, chernodub commented on apps/vanilla/src/namespaces/PageHandler.ts
> +    }
To increase readability of the code, consider moving such transformations into their own functions. This would also make your code more self-documenting

2022-07-28 04:56 UTC, chernodub commented on apps/vanilla/src/namespaces/SortHandler.ts
> +import { Params } from '@js-camp/core/models/params';
Seems like `Params` name is too generic. Params could be anything, parameters of the function, parameters of the application, etc. Consider making a name more specific, please

2022-07-28 04:56 UTC, chernodub commented on apps/vanilla/src/pages/index.html
> +      <button type="button" class="pagination__button last-page-button">last</button>
Actually, you could apply BEM modifiers in this case: `pagination__button_last` and `pagination__button_first`. Check out this [BEM cheat sheet](https://9elements.com/bem-cheat-sheet/) for better understanding

2022-07-28 04:56 UTC, chernodub commented on apps/vanilla/src/script/init.ts
> +  renderPagination(0, 0);
For future, [prefer avoiding ordered params](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#avoid-ordered-params-in-constructorsfunctions)

2022-08-04 15:17 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-11 07:21 UTC, merged