Feature/jc19 464 authorization react
saritasa-nest/camp-js-2022-loc-tran pull request #12
Opened 2022-08-29 01:13 UTC by LocTran-saritasa

2022-08-29 11:59 UTC, pavelzadorin-saritasa requested changes

2022-08-29 11:59 UTC, pavelzadorin-saritasa commented on apps/react/src/shared/components/Header/Header.tsx
> +// I disabled this eslint rule because this function contains a large of jsx code.
I think this was a sign that the component is overloaded and needed to be decomposed. :)
For example, I see 2 components that stand out logically and functionally from the Header, these are Navigation and User Menu. If you take them out into separate components, then each separately will be quite small.

2022-08-29 11:59 UTC, pavelzadorin-saritasa commented on apps/react/src/features/auth/components/RegisterForm/RegisterForm.tsx
> +  const { snackbarConfig, openSnackbar, handleCloseSnackbar } = useSnackbar();
Working with a Snackbar looks overcomplicated. I would suggest thinking about 2 points:
- do we need to configure the Snackbar parameters through the hook? why not use conditional rendering, e.g:
```
{error &&
  <MySnackbar
        message={error}
        severity='error'
    />
}
```
- encapsulation of the Snackbar display logic inside the Snackbar looks reasonable, at the moment the parent component (e.g. RegisterForm) receives the Open status and CloseHandler from the hook and does not use them in any way, only passes them to the Snackbar, so why does the parent need to operate with these entities at all? why can't the Snackbar manage the opening status itself internally and handle the closing? From the parent, then only the message and type of error will be needed, well, maybe HideDuration yet and the forms will become much simpler.

2022-08-29 11:59 UTC, pavelzadorin-saritasa commented on apps/react/src/routes/RootRouter.tsx
> +import { HOME_PAGE } from './guards/IsNotLoggedIn';
The home page is logically the entity of the project level, and not a specific guard, it looks strange that we import this constant from the guard. It is worth taking this constant to a higher level and then importing both here and into the guard.

2022-08-29 11:59 UTC, pavelzadorin-saritasa commented on apps/react/src/features/genres/routes.tsx
> +    element: <Header />,
It seems to me that this component would be necessary for all pages of the site (excepts auth) if there were a lot of them (and genres, and anime, etc.) and in order not to describe it in each individual router, it makes sense to transfer Header to the root router or root layout.

2022-08-29 11:59 UTC, pavelzadorin-saritasa commented on apps/react/src/features/auth/components/RegisterForm/RegisterForm.tsx
> +        navigate(HOME_PAGE);
As I understand it, `IsNotLoggedIn` does the same job? Then let's not repeat the implementation and leave it only in the guard.

2022-08-29 11:59 UTC, pavelzadorin-saritasa commented on apps/react/src/features/auth/components/RegisterForm/RegisterForm.tsx
> +          result.payload.data[key].forEach(error =>
It looks like a work for `Mapper.fromDto`, if the mapper will immediately prepare validation errors in Formik format, then it will be enough just to pass it through the method [setErrors](https://formik.org/docs/api/formik#seterrors-fields--field-string-string---void)

2022-08-29 11:59 UTC, pavelzadorin-saritasa commented on apps/react/src/features/auth/components/FormTextField/FormTextField.tsx
> +  [key: string]: string;
This approach completely breaks the typing, in fact, now the Props type is almost equivalent to `any`.
If you want to allow other valid props, then make it inherit from the base type, like so:
`interface Props extends TextFieldProps`

2022-08-29 11:59 UTC, pavelzadorin-saritasa commented on apps/react/src/features/auth/components/FormTextField/FormTextField.tsx
> +      helperText={meta.touched && meta.error}
Have you looked at https://stackworx.github.io/formik-mui/?
It seems to me that this library will completely abandon this wrapper.

2022-08-30 03:09 UTC, pavelzadorin-saritasa commented on apps/react/src/shared/components/MySnackbar/MySnackbar.tsx
> +export const MySnackbar = SnackbarComponent;
`my snackbar` is a semantically weak name, how exactly does that reflect the meaning of this component?

2022-08-30 04:06 UTC, golovachev-yaroslav requested changes

2022-08-30 04:06 UTC, golovachev-yaroslav commented on apps/react/src/shared/components/Header/Header.tsx
> +              sx={{
Let's use css instead of css in js, it makes code more overloaded.

2022-08-30 04:06 UTC, golovachev-yaroslav commented on apps/react/src/shared/components/LoadingPage/LoadingPage.tsx
> +  <>
Unnecessary `<></>`
It's good for multiple children:
```
return (
  <Avatar />
  <Dropdown>
)
```
It wouldn't work



And `<></>` good here.
```
return (
  <>
    <Avatar />
    <Dropdown>
  </>
)
```

2022-08-30 04:06 UTC, golovachev-yaroslav commented on apps/react/src/shared/components/MySnackbar/MySnackbar.tsx
> +    <>
The same with `<></>`.

2022-08-30 04:06 UTC, golovachev-yaroslav commented on apps/react/src/shared/components/MySnackbar/MySnackbar.tsx
> +      <Button color="secondary" size="small" onClick={handleClose}>
Missed type.

2022-08-30 05:39 UTC, golovachev-yaroslav requested changes

2022-08-30 05:39 UTC, golovachev-yaroslav commented on apps/react/src/shared/components/MySnackbar/MySnackbar.tsx
>    /** Snackbar message. */
It would be better to call it AppSnackbar

2022-08-31 07:48 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-31 07:48 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/auth/components/RegisterForm/RegisterForm.tsx
> +  setErrors: (fields: { [field: string]: string; }) => void;
```suggestion
  setErrors: (fields: Record<string, string>) => void;
```

2022-08-31 07:48 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/auth/components/RegisterForm/RegisterForm.tsx
> +          placeholder="EX: abc@example.com"
```suggestion
          placeholder="e.g. abc@example.com"
```

2022-08-31 11:27 UTC, pavelzadorin-saritasa requested changes

2022-08-31 11:27 UTC, pavelzadorin-saritasa commented on apps/react/src/routes/guards/IsLoggedIn.tsx
> +import { LOGIN_PAGE } from '../../features/auth/pages/RegisterPage/RegisterPage';
You define the `LOGIN_PAGE` constant in the `RegisterPage` file only because you needed it there the first time, but there is no logical connection between them. And as a result, such strange imports are obtained (import login from registration, what? why not from login?), additionally, another developer will not understand where to look for this constant, if he needs it (but he does not know what it is called), he will simply create a new one.
When adding something to the code, you always need to think where it is more correct to place this functionality and often this is not the place where it's used.
In my opinion, `LOGIN_PAGE` logically refers to login or routing, and this constant should be declared somewhere in the files next to one of these entities. Since you have a lot of constants defining paths, maybe you should create a corresponding section in your routing, something like Paths file?
p.s. This is the same problem that was with `HOME_PAGE`, but in general it remains...

2022-08-31 11:27 UTC, pavelzadorin-saritasa commented on apps/react/src/store/auth/slice.ts
> +        if (action.payload instanceof Token) {
Look at a way to specify types for `createAsyncThunk`: https://redux-toolkit.js.org/usage/usage-with-typescript#createasyncthunk
This should allow you to give up so many type guards.

2022-09-05 07:04 UTC, pavelzadorin-saritasa approved these changes

2022-09-26 02:15 UTC, closed without merging