Feature/jc19 474 anime list react
saritasa-nest/camp-js-2022-loc-tran pull request #13
Opened 2022-08-30 10:05 UTC by LocTran-saritasa

2022-08-31 04:16 UTC, artem-sotnichenko-saritasa requested changes

2022-08-31 04:16 UTC, artem-sotnichenko-saritasa commented on apps/react/src/store/anime/state.ts
> +  readonly animeList: Anime[];
Not sure if you had reudx lecture yet, but please normalize your store. It's really easy with redux toolkit, greatly improve perfomance and simplify work with connected entities

2022-09-02 03:34 UTC, panov-aleksey-saritasa commented on apps/react/src/features/anime-list/pages/AnimePage/AnimePage.tsx
> +    </Grid>
If it's not ready yet, let's remove it then

2022-09-02 03:34 UTC, panov-aleksey-saritasa commented on apps/react/src/store/anime/state.ts
> +export const animeAdaptor = createEntityAdapter<Anime>();
```suggestion
export const animeAdapter = createEntityAdapter<Anime>();
```

2022-09-02 03:34 UTC, panov-aleksey-saritasa commented on apps/react/src/store/anime/slice.ts
> +        animeAdaptor.setAll(state as State, action.payload);
Why do you need type-cast `state` here?

2022-09-02 03:34 UTC, panov-aleksey-saritasa commented on apps/react/src/features/anime-list/components/AnimeList/AnimeList.tsx
> +      <Skeleton variant="rectangular" width={80} height={80} />
Let's not mix up mui style props and classes. You could use `Box` component instead of `div`

2022-09-02 03:34 UTC, panov-aleksey-saritasa commented on apps/react/src/store/auth/state.ts
> +  isAuthorized: true,
Why did you change it? I believe it should be `false` by default, since at first we need to get info about current authorization

2022-09-02 04:35 UTC, golovachev-yaroslav approved these changes

2022-09-02 04:35 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/Anime/Anime.tsx
> +const placeholder = (text: string): string => text ? text : 'Empty';
This is a function, functions should starts with a verb. `getPlaceholder` - could be.

2022-09-02 07:44 UTC, LocTran-saritasa commented on apps/react/src/store/anime/slice.ts
> +        animeAdaptor.setAll(state as State, action.payload);
The passed state is  of type `WritableDraft<>` type. But the method `setAll` of `animeAdaptor` doesn't accept it so I have to use type-cast here. I have searched for an alternative but I can't found it.

2022-09-02 10:59 UTC, artem-sotnichenko-saritasa approved these changes

2022-09-02 11:04 UTC, artem-sotnichenko-saritasa commented
@LocTran-saritasa Usually we place not one but many skeletons, [youtube](https://www.youtube.com/) is a great example.
Also your skeleton is different from your actual card.

2022-09-04 11:40 UTC, gevorg-gevorgyan-saritasa approved these changes

2022-09-05 11:21 UTC, golovachev-yaroslav approved these changes

2022-09-10 13:07 UTC, pavelzadorin-saritasa approved these changes

2022-09-10 13:07 UTC, pavelzadorin-saritasa commented on apps/react/src/store/anime/dispatchers.ts
> +const DEFAULT_QUERY_PARAMS = new PaginationParams({
how is this different from `DEFAULT_QUERY_PARAMS` of service `animeService`? maybe you can reuse `animeService` const instead of duplicating the code?

2022-09-26 02:15 UTC, closed without merging