Feature/jc19 484 anime management react
saritasa-nest/camp-js-2022-loc-tran pull request #14
Opened 2022-09-05 15:19 UTC by LocTran-saritasa

2022-09-06 03:44 UTC, golovachev-yaroslav requested changes

2022-09-06 03:44 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/AnimeFilter/components/search/search.tsx
> +      id=""
Why empty value? Maybe remove `id` at all?

2022-09-06 03:44 UTC, golovachev-yaroslav commented on apps/react/src/shared/components/TabPanel/TabPanel.tsx
> +      {...other}
If you pass `role="button"` in `...other` props, it will override `role="tabpanel"` because it placed before `...other`. 
For preventing this issue you need to add `{...other}` as the first attribute in the  `div`.
`<div {...other} role="...`

2022-09-11 15:18 UTC, artem-sotnichenko-saritasa approved these changes

2022-09-11 15:18 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime-list/components/AnimeList/AnimeList.tsx
> +      <AnimeSkeleton />
I suggest looping with a `map` here

2022-09-11 15:18 UTC, artem-sotnichenko-saritasa commented on apps/react/src/features/anime-list/components/AnimeList/AnimeList.tsx
> +      {list.length > 0 ? list : skeleton}
If there are no items you should show something like a message "No items", not the skeleton.

2022-09-11 15:18 UTC, artem-sotnichenko-saritasa commented on apps/react/src/shared/components/TabPanel/TabPanel.tsx
> +  readonly children?: React.ReactNode;
Prefer importing instead of using `React` object.

2022-09-12 06:05 UTC, golovachev-yaroslav approved these changes

2022-09-12 06:05 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/AnimeFilter/AnimeFilter.tsx
> +        <Tab label="Search" {...passTabIdentifierProps(0)} />
I think much beeter to use enum here
```
enum TabType {
  Search = '0',
  Field = '1',
  Type = '2',
}
```

2022-09-12 06:05 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/AnimeFilter/AnimeFilter.tsx
> +      <TabPanel value={tabValue} index={0}>
`index={TabType.Search}`

2022-09-12 06:05 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/AnimeFilter/AnimeFilter.tsx
> +        <Tab label="Field" {...passTabIdentifierProps(1)} />
`{...passTabIdentifierProps(TabType.Search)}`

2022-09-12 09:32 UTC, pavelzadorin-saritasa requested changes

2022-09-12 09:32 UTC, pavelzadorin-saritasa commented on apps/react/src/features/anime-list/components/AnimeFilter/components/search/search.tsx
> +const SearchComponent: FC<Props> = ({ queryParams, onChange }) => (
I see violations of component encapsulation, now the `Search` component knows that the parameters are stored in `QueryString`, and its parent component is forced to know how the search component stores its value (`event.target.value`).
This can be greatly improved: the search component only needs the search string, so you can only pass it, not the whole `queryParams`. And the `onChange` prop can also work directly with the search string, i.e. `event.target.value` must be processed inside the `Search` component, and the parent will immediately receive the search string instead of whole event.
As a result, the search component receives the search string as input and returns the modified string to the parent, this is a good encapsulation of the logic of the `Search` component.

2022-09-12 09:32 UTC, pavelzadorin-saritasa commented on apps/react/src/features/anime-list/components/AnimeFilter/AnimeFilter.tsx
> +  const handleSelectChange =
Think of a better name.

2022-09-12 09:32 UTC, pavelzadorin-saritasa commented on apps/react/src/features/anime-list/components/AnimeFilter/components/sort/sort.tsx
> +const SortComponent: FC<Props> = ({ queryParams, onFieldChange }) => (
I think encapsulation can be improved here, as well as for Search.

2022-09-12 09:32 UTC, pavelzadorin-saritasa commented on apps/react/src/features/anime-list/components/AnimeFilter/components/type/type.tsx
> +const TypeComponent: FC<Props> = ({ queryParams, handleTypeChange }) => <FormControl fullWidth>
I think encapsulation can be improved here, as well as for Search.

2022-09-12 09:32 UTC, pavelzadorin-saritasa commented on apps/react/src/store/anime/dispatchers.ts
> +export enum SortDirection {
you define the sorting field in the model, and the sorting direction in the dispatcher, why? I do not see the logical difference between these entities, even more, they are always used together, and probably they should be defined in one place.

2022-09-13 03:34 UTC, golovachev-yaroslav approved these changes

2022-09-13 03:34 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/AnimeFilter/AnimeFilter.tsx
> +        <Tab label="Search" {...passTabIdentifierProps(TabType.SearchTab)} />
`TabType.SearchTab`  too many Tab words. Let's rename to `TabType.Search`.

2022-09-13 09:47 UTC, golovachev-yaroslav approved these changes

2022-09-14 04:16 UTC, golovachev-yaroslav approved these changes

2022-09-16 02:53 UTC, pavelzadorin-saritasa approved these changes

2022-09-16 02:53 UTC, pavelzadorin-saritasa commented on apps/react/src/features/anime-list/components/AnimeFilter/components/type/type.tsx
> +  readonly handleTypeChange: (value: readonly string[]) => void;
The component receives and returns the same type of data: the selected movie types. Then it is logical that the format for transmitting this data should also be the same, do not forget about the consistency of approaches.
Сonsumer does need to worry about concatenating a string as input, but return an array of strings at the output, this is wrong.
Since we are implementing the Anime type selector component, I consider `AnimeType[]` to be the most logical type for working with it, both as an input and as a return value, a list of types was passed, a list of types was received, brilliantly simple!
Then the component will be truly independent, it can be used in any type selection scenario, regardless of where and how these types will be used later.

2022-09-16 04:38 UTC, golovachev-yaroslav approved these changes

2022-09-26 02:15 UTC, closed without merging