Feature/jc19 504 item management react
saritasa-nest/camp-js-2022-loc-tran pull request #16
Opened 2022-09-09 09:03 UTC by LocTran-saritasa

2022-09-09 09:23 UTC, golovachev-yaroslav requested changes

2022-09-09 09:23 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/Anime/Anime.tsx
> +  const handleCloseDeleteAnime = () => setOpenDelete(false);
Please add empty rows between `hadle...` functions

2022-09-09 09:23 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/Anime/Anime.tsx
> +        to={`${anime.id}?${searchParams.toString()}`}
Let's move path to const 

`const to = `${anime.id}?${searchParams.toString()}`;`

2022-09-09 09:23 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/ManagementForm/ManagementForm.tsx
> +  const addGenre = (name: string) => {
Please add empty rows between const

2022-09-09 09:23 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/ManagementForm/components/FormChipsSelect/FormChipsSelect.tsx
> +const delayOnSearch = 300;
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#naming-convention

PLease rename to `DELAY_ON_SEARCH`.

2022-09-09 09:23 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/ManagementForm/components/FormChipsSelect/FormChipsSelect.tsx
> +  const onSearchChange = (event: SyntheticEvent, value: string) => {
It should be `handleSearchChange`. The prefix `on` good if you receive props, not for handling something.

2022-09-09 09:23 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/ManagementForm/components/FormDateSelect/FormDateSelect.tsx
> +  readonly handleDateChange: (date: Date) => void;
This is `props`. It should be `onDateChange`.

2022-09-09 09:23 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/ManagementForm/components/FormDateSelect/FormDateSelect.tsx
> +  const onDateChange = (newValue: Date | null) => {
It should be handleDateChange.

2022-09-09 09:23 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/ManagementForm/components/ImageSelect/ImageSelect.tsx
> +  readonly handleChange: (image: File) => void;
`onChange`

2022-09-09 09:23 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/ManagementForm/components/ImageSelect/ImageSelect.tsx
> +        <img className={styles['selector__image']} src={imageUrl} />
Missed required `alt` attribute.

2022-09-09 09:52 UTC, golovachev-yaroslav approved these changes

2022-09-09 10:28 UTC, golovachev-yaroslav requested changes

2022-09-09 10:28 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/ManagementForm/ManagementForm.tsx
> +            initialValue={
Please move to const, it makes more readable the code.

2022-09-09 10:28 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/ManagementForm/ManagementForm.tsx
>              handleDateChange={handleEndDateChange}
It should be onDateChange, bacause it's props.

2022-09-09 10:28 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/ManagementForm/components/ChipsEditor/ChipsEditor.tsx
> +  const addGenre = (name: string) => {
Please add empty rows between handle functions.

2022-09-09 10:28 UTC, golovachev-yaroslav commented on apps/react/src/features/anime-list/components/ManagementForm/components/ChipsEditor/ChipsEditor.tsx
> +        addOption={addGenre}
Passed functions should starts with prefix on

2022-09-13 03:29 UTC, golovachev-yaroslav approved these changes

2022-09-14 17:02 UTC, artem-sotnichenko-saritasa approved these changes

2022-09-16 06:03 UTC, golovachev-yaroslav approved these changes

2022-09-26 02:15 UTC, closed without merging