Feature/jc19 355 authorization feature for vanilla js app
saritasa-nest/camp-js-2022-loc-tran pull request #2
Opened 2022-07-12 08:43 UTC by LocTran-saritasa

Authorization feature for vanilla js app

2022-07-13 06:37 UTC, golovachev-yaroslav requested changes

2022-07-13 06:37 UTC, golovachev-yaroslav commented on apps/vanilla/src/script/renderToUI.ts
> +          />
Do not leave closing `>` on the new line

2022-07-14 06:26 UTC, elena-dragunova requested changes

2022-07-14 06:26 UTC, elena-dragunova commented on libs/core/models/loginData.ts
> +  /** User 's email. */
Delete space after 'User' please

2022-07-14 06:26 UTC, elena-dragunova commented on libs/core/models/loginData.ts
> +  /** User 's password. */
the same

2022-07-14 06:26 UTC, elena-dragunova commented on libs/core/models/token.ts
> +  /** Refresh token string. */
It's not necessary to include data type in the description

2022-07-15 10:38 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/script/accessPage.ts
> +  }
I would suggest you to make auth guard from this code. For example, `unauthorizedGuard`(I'm not sure about this naming). Then use it in your `register.ts/login.ts`.

```ts
document.addEventListener("DOMContentLoaded", async() => {
  await unauthorizedGuard();
  initRegisterForm()
}
```

2022-07-15 10:38 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/script/accessPage.ts
> +  if (isLoggedIn === true) {
For there is no need to use it like this for simple booleans

```suggestion
  if (isLoggedIn) {
```

2022-07-15 10:38 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/script/init.ts
> +  const form = document.querySelector('.form');
Please use generic here to avoid casting
```suggestion
  const form = document.querySelector<HTMLFormElement>('.form');
```

2022-07-15 10:38 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/script/renderToUI.ts
> +export function showErrorRegister(errorList: string[]): void {
Missing readonly for array

2022-07-15 10:38 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/services/getUserData.ts
> +  if (isValidToken === false) {
Same about booleans

2022-07-15 11:27 UTC, elena-dragunova approved these changes

2022-07-17 17:46 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-17 17:46 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/namespaces/middleware.ts
> +    if (isValidToken === false) {
```suggestion
    if (!isValidToken) {
```

2022-07-17 17:46 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/services/getUserData.ts
> +  }
If you catching and than just throwing same error, I think you should just remove "try catch" construction.

2022-07-18 04:54 UTC, panov-aleksey-saritasa requested changes

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/namespaces/submitHandler.ts
> +        localStorage.setItem('REFRESH_TOKEN', auth.refreshToken);
Please, move out interactions with `localStorage` from the UI to the methods responsible for that, I suppose in your case it's `login`, `register` and etc.

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/namespaces/submitHandler.ts
> +    localStorage.removeItem('REFRESH_TOKEN');
Same

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/script/constants.ts
> +export const REFRESH_URL = '/api/v1/auth/token/refresh/';
To not write `_URL` every time, you could group it with `namespace`, something like this:
```ts
export namespace ApiUrl {
  export const login = '/api/v1/auth/login/';
  ...
}
```
And the same for pages

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/register/register.css
> +
Do not use both `camelCase` and `kebab-case` simultaneously, choose one approach and stick to it everywhere

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/register/register.css
> +
And, if I understand your intent correctly, it's better to name this class as `.form__submit-button`, or make use of BEM [modifiers](https://en.bem.info/methodology/quick-start/#modifier) and implement two classes: `form__button` and `form__button_submit`

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/register/register.css
> +}
As I see, `register.css` duplicates some styles from `login.css` 1-to-1. Consider avoiding code duplication

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/services/token.ts
> +  }
It's the same as
```ts
throw error as Error
```
So you probably don't need to do this in the first place

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/services/login.ts
> +    showErrorLogin(errorList);
Your business methods shouldn't do anything for UI, please, do not violate abstraction layers

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/services/login.ts
> +    throw new Error((error as Error).message);
```suggestion
    throw error;
```

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on libs/core/models/httpError.ts
> +  /** List of error. */
```suggestion
  /** List of errors. */
```

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on libs/core/models/httpError.ts
> +export class HTTPError extends Immerable {
I suppose since you have `HttpErrorMapper`, it's logical to name this model `HttpError`, right?

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/services/getUserData.ts
> +  }
Are you going to do *verifyToken + refreshToken* stuff in every business method? 🙃
Consider doing this in  `axios` interceptor. Actually, it's not required to validate tokens, you just need to check for [401](https://www.webfx.com/web-development/glossary/http-status-codes/what-is-a-401-status-code/) error from axios and then try to refresh token

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/namespaces/middleware.ts
> +  export async function isNotLoggedIn(): Promise<void> {
It seems strange that this function returns `void`, with such name I would expect it to return `boolean`

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/namespaces/middleware.ts
> +  export async function isNotLoggedIn(): Promise<void> {
And as I see, this function does too many things, consider revising it

2022-07-18 04:54 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/namespaces/submitHandler.ts
> +        const auth = await login(loginData);
We usually don't create domain entites in UI layer. If `LoginData` is just data we need to pass into `login` method, consider making it `interface` instead

2022-07-29 03:47 UTC, chernodub approved these changes
Very good job!

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/api/interceptors.ts
> +    },
Please never ignore linter errors. Always resolve them or disable (with specifying a reason via docs)

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/api/interceptors.ts
> +  if (localStorage.getItem('ACCESS_TOKEN') !== null) {
Please use named constants instead of hard-coded strings. This way your code would be mistypings-prone and easier for refactoring

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/api/interceptors.ts
> +  throw error;
Are you sure it's a good idea throwing an error in case you successfully refreshed the token?

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/global/input-group.css
> +.form__buttonGroup {
Please keep consistent naming, we don't use camel case for naming BEM classes

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/global/variables.css
>    /* Using html color names here only for showcase,
Please remove the boilerplate text, this was needed for initialization only

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/namespaces/apiUrl.ts
> +  export const refresh = '/api/v1/auth/token/refresh/';
I'd recommend leveraging reusing of `api/v1`. This way you could have a single source of truth for api version, and there won't be a need to global-replace things, just change a single variable

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/namespaces/middleware.ts
> +export namespace Middleware {
Middleware is too generic, it could be any function that lies between app-level functionality and platform-level. Please use terminology only when you 100% understand it. Basically, for now, this group only has api-related requests, please consider adjusting the name

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/namespaces/middleware.ts
> +  export function checkIsLoggedIn(): void {
From the name, I would assume this function only queries the information about whether the user is logged in or not (thus, it would just return a boolean) without making any side effects. Please consider providing a more explicit name for commands and queries https://en.wikipedia.org/wiki/Command%E2%80%93query_separation

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/namespaces/submitHandler.ts
> +        showErrorLogin(['Email and password is required!']);
```suggestion
        showErrorLogin(['Email and password are required!']);
```

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/namespaces/submitHandler.ts
> +      if (email !== null && firstName !== null && lastName !== null && password !== null && retypePassword !== null) {
Please consider creating some reusable validators for this, so as not to repeat the `!== null` every time, try making your code better readable

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/namespaces/submitHandler.ts
> +        const newAccount = new Account({
It's a good thing you unified these properties into a single entity 👍  
But, do you really need a class for this? Maybe a simple interface would be just enough?

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/pages/login/index.html
> +      </div>
Pls make sure your indents are consistent. To automate this, I recommend using Prettier for auto-formatting the HTML

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/pages/register/index.html
> +          <input name="password" required autocomplete="on" type="password" placeholder="Type your password" class="form__label-input form__label-password" />
Consider using BEM modifier to set input as password `form__label-input_password`. According to BEM spec, one item can not be two elements at the same time.

2022-07-29 03:47 UTC, chernodub commented on apps/vanilla/src/services/auth.ts
> +    localStorage.setItem(REFRESH_TOKEN, auth.refreshToken);
For future, it is recommended to wrap storage calls into it's own entity, this way you could seamlessly swap storage with other (e.g. IndexedDB).

2022-07-29 03:47 UTC, chernodub commented on libs/core/mappers/account.mapper.ts
> +      password: account.password,
Please don't ignore linter errors. For this case you could create a local `eslintrc` file that would disable the `naming-convention` rule for dto-related files

2022-08-11 07:29 UTC, merged