Feature/jc19 360 details for a selected film
saritasa-nest/camp-js-2022-loc-tran pull request #6
Opened 2022-07-20 03:04 UTC by LocTran-saritasa

Details for a selected film.

2022-07-21 06:58 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/script/renderDetail.ts
> +  const titleNode = document.createElement('span');
Maybe `titleElement`?

2022-07-22 02:45 UTC, panov-aleksey-saritasa requested changes

2022-07-22 02:45 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/global/header.css
> +.header__authen {
What is *authen*?

2022-07-22 02:45 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/namespaces/PageHandler.ts
> +    const totalPage = Number.parseInt(count, DECIMAL) / LIMIT;
I think you don't need `DECIMAL` constant, it's clear what does `10` mean in context of `parsetInt` 🙂

2022-07-22 02:45 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/script/constants/localStorageName.ts
> +export const ANIME_LS = 'ANIME_ID';
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions

2022-07-22 02:45 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/services/fetchAnime.ts
> +
In the context of frontend a *route* usually means navigation-related stuff. Better to use *url* here to not confuse anyone

2022-07-22 02:45 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/namespaces/middleware.ts
> +  }
Right now this function does two separate things at the same time: checks if there are tokens and implicitly verifies/refreshes them. Consider separating this stuff into different functions

2022-07-22 02:45 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/namespaces/middleware.ts
> +  }
About doing token refresh, [axios.interceptors](https://axios-http.com/docs/interceptors) is generally a good place to do this stuff, you need to just check for [401](https://www.webfx.com/web-development/glossary/http-status-codes/what-is-a-401-status-code/) errors from axios and try to do refresh token logic

2022-07-22 02:45 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/services/auth.ts
> +      return errorList;
duplicates error catching from the `login` function, consider at least moving this out as a function

2022-07-22 02:45 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/services/auth.ts
> +      const errorData = HttpErrorMapper.fromDto(error as HttpErrorDto);
use `instanceof HttpErrorDto` check instead of typecasting

2022-07-22 02:45 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/services/auth.ts
> +  export async function login(data: LoginData): Promise<Array<string> | null> {
```suggestion
  export async function login(data: LoginData): Promise<string[] | null> {
```

2022-07-22 02:45 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/services/auth.ts
> +      return errorList;
Consider throwing `HttpError` instead

2022-07-22 02:45 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/services/auth.ts
> +      return errorList;
From the signature of this function is very very unclear that `Array<string>` is actually array of error messages 🥲

2022-07-22 05:12 UTC, LocTran-saritasa commented on apps/vanilla/src/global/header.css
> +.header__authen {
I mean authenticate. Let me fix it :sweat_smile:

2022-07-22 06:25 UTC, LocTran-saritasa commented on apps/vanilla/src/services/auth.ts
> +      return errorList;
I want to get the error message from BE and display on UI. If I throw an error here, I can't get these messages. Is there any solution for this?

2022-07-22 06:52 UTC, LocTran-saritasa commented on apps/vanilla/src/services/auth.ts
> +      const errorData = HttpErrorMapper.fromDto(error as HttpErrorDto);
I got this error while use instanceof HttpErrorDto
> 'HttpErrorDto' only refers to a type, but is being used as a value here. ts(2693)

2022-07-22 15:06 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/api/interceptors.ts
> +      'Api-Key': CONFIG.apiKey,
You could use constant API_HEADER already have

2022-07-22 15:19 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/namespaces/PageHandler.ts
> +  export function goToPageByNum(newPage: number): void {
Avoid contraction, please improve the funtion name `goToNextPage` is ok?
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions

2022-07-25 01:41 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/namespaces/middleware.ts
> +  }
Let's use `isAuthorized` function to reduce code duplication

2022-07-25 03:24 UTC, thanhnguyen-saritasa commented on libs/core/models/detail.ts
> +export class Detail extends Anime {
I think the name of file and class is common meaning.
Would you please update it to 'AnimeDetail'

2022-07-25 03:35 UTC, thanhnguyen-saritasa commented on libs/core/mappers/anime.mapper.ts
> +    return {
Do you see the IDE warning missing property [immerable]?
Please return new Enime()

2022-07-25 03:53 UTC, thanhnguyen-saritasa commented on libs/core/dtos/detail.dto.ts
> +  readonly title_eng: string;
Please avoid contraction.
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions
'title_english'

2022-07-25 03:53 UTC, thanhnguyen-saritasa commented on libs/core/dtos/detail.dto.ts
> +  readonly title_jpn: string;
Same above suggestion, please improve it

2022-07-25 03:55 UTC, thanhnguyen-saritasa commented on libs/core/dtos/anime.dto.ts
> +  readonly title_eng: string;
please update property name
https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions

2022-07-25 04:03 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/services/token.ts
> +  return TokenMapper.fromDto(response.data);
What will it happenning when API request failed? I think we could handle it in try ... catch

2022-07-25 04:06 UTC, LocTran-saritasa commented on libs/core/dtos/detail.dto.ts
> +  readonly title_eng: string;
Because this is dto interfaces so I had to name it like that due to the data response from BE.

2022-09-26 02:15 UTC, closed without merging