Feature/jc19 400 init table view angular
saritasa-nest/camp-js-2022-loc-tran pull request #7
Opened 2022-07-26 16:37 UTC by LocTran-saritasa

2022-07-27 04:42 UTC, timofei-maximov-saritasa requested changes
Please, check task description.
https://saritasa.slack.com/archives/C02UTQPRW7R/p1658889657459299

2022-07-27 04:42 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +  <tr class="table__row" *ngFor="let anime of animes">
missing `trackBy`

2022-07-27 04:42 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +<table class="table" *ngIf="(animeList$ | async) as animes; else Loading">
```suggestion
<table class="table" *ngIf="(animeList$ | async) as animeList; else Loading">
```

2022-07-27 04:42 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +</table>
You can use [material table](https://material.angular.io/components/table/overview)

2022-07-27 04:42 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.spec.ts
> +});
Do you really need tests?

2022-07-28 04:38 UTC, TienLuu-Saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +  public constructor(private readonly animeService: AnimeService) {
> You can omit access modifier if you are not going to use `animeService` outside of `constructor`

2022-07-29 04:39 UTC, timofei-maximov-saritasa approved these changes

2022-07-29 04:39 UTC, timofei-maximov-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.html
> +  class="mat-elevation-z8"
Missing `trackBy`
https://angular.io/api/core/TrackByFunction
https://material.angular.io/cdk/table/overview#trackby

2022-08-10 04:51 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-10 04:51 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +  public readonly columnTitles = ['Image', 'Title English', 'Title Japanese', 'Aired start', 'Type', 'Status'];
Don't forget about readonly

2022-08-11 07:04 UTC, chernodub requested changes
@LocTran-saritasa please do not open PRs with several features un-merged at the same time. As you can see, this PR contains more than 100 files highlighted. You should merge the branch to the same place where you opened it, in order to avoid such cases.

e.g: If you opened `feature/angular-table` from `feature/vanilla-authorization`, and `feature/vanilla-authorization` is not yet closed, you should merge `feature/angular-table` to `feature/vanilla-authorization` directly. Github takes diff from branch to branch, that's why everything's highlighted

2022-08-11 07:04 UTC, chernodub commented on libs/core/mappers/account.mapper.ts
> +      password: account.password,
Please never ignore eslint errors. In this case you can disable the rule

2022-08-12 02:51 UTC, pavel-romanov8 requested changes

2022-08-12 02:51 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.html
> +    <td mat-cell *matCellDef="let anime">{{ anime.titleJapanese || 'Not found'}}</td>
Let's create some placeholder pipe in order to avoid code duplication

2022-08-12 02:51 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.html
> +      <img class="table__row-image" src="{{ anime.image }}" alt="" />
Usually we prefer using a bit different syntax:
```suggestion
      <img class="table__row-image" [src]="anime.image" alt="" />
```

2022-08-12 02:51 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +  /** Anime data response from BE. */
Components should know nothing about the data source, please omit mentions of any responses and BE

2022-08-12 02:51 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime-table/anime-table.component.ts
> +  /** Anime data response from BE. */
It would be great if you get familiar with our apps architecture on wiki - https://wiki.saritasa.rocks/frontend/frameworks/architecture/

2022-08-12 02:51 UTC, pavel-romanov8 commented on apps/angular/src/app/features/anime/anime.component.ts
> +  styleUrls: [],
Please, omit the styles if you don't have any. Also, be consistent with your change detection strategies. For `AnimeTableComponent` you are using `OnPush`, but here it is default

2022-08-12 02:51 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +  private apiUrl = this.appConfig.apiUrl + ANIME_URL;
Please, use URL object instead of plain string. It provides you a better interface and less error-prone compare to strings

2022-08-12 02:51 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +  private apiUrl = this.appConfig.apiUrl + ANIME_URL;
```suggestion
  private readonly apiUrl = this.appConfig.apiUrl + ANIME_URL;
```

2022-08-12 02:51 UTC, pavel-romanov8 commented on apps/angular/src/core/services/anime.service.ts
> +  private apiUrl = this.appConfig.apiUrl + ANIME_URL;
You already have `apiUrl` in `appConfig` let's give it a more specific name in order to avoid confusions

2022-08-12 02:51 UTC, pavel-romanov8 commented on apps/angular/src/shared/pipe/date-to-locale.pipe.ts
> +export class DateToLocalePipe implements PipeTransform {
Angular already have a rich pipes functionality, especially for dates. Check it out - https://angular.io/api/common/DatePipe

2022-08-12 02:51 UTC, pavel-romanov8 commented on apps/vanilla/src/api/interceptors.ts
> +export const API_HEADER = 'Api-Key';
Why do you need to export it?

2022-08-12 02:51 UTC, pavel-romanov8 commented on apps/vanilla/src/script/init.ts
> +  if (form !== null) {
I'm not sure whether you are using the code in the angular or not. If you are not, then please, try to organize your PR more precisely so the people that review your code won't be confused

2022-08-12 07:21 UTC, LocTran-saritasa commented on apps/vanilla/src/script/init.ts
> +  if (form !== null) {
I have re-organize my PR but this branch base on branch authorization vanilla. Because branch authorization vanilla has changed too much due to code review after I created so it cause this 😢  But just this branch, future branches based on this won't be confused.

2022-08-12 08:00 UTC, dbitkovski requested changes

2022-08-15 09:45 UTC, chernodub approved these changes

2022-09-26 02:15 UTC, closed without merging