Feature/jc19 432 authorization angular
saritasa-nest/camp-js-2022-loc-tran pull request #9
Opened 2022-08-09 08:48 UTC by LocTran-saritasa

2022-08-11 04:43 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/auth/login/login.component.ts
> +  /** Store error data response from BE. */
What BE stands for?

2022-08-11 04:43 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +  public constructor(private readonly http: HttpClient, private readonly tokenService: TokenService) {}
Please place them each on new line

2022-08-11 04:43 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/auth/login/login.component.ts
> +  public readonly loginData$ = new Subject<LoginData>();
You shouldn't expose subjects (making them public).

2022-08-11 04:43 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/auth/login/login.component.ts
> +          catchError(this.handleLoginError.bind(this)),
Prefer not using `bind`, because it brings unnecessary complexity. In you case you can refactor it to 
```suggestion
          catchError(error => this.handleLoginError(error)),
```

2022-08-11 04:43 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/auth/login/login.component.ts
> +    this.login$ = this.loginData$.pipe(
I think you overcomplicate logic. Instead of using `loginData$` subject and `login$`, you can just move this logic and `ngOnInit` logic into `onSubmit` method.

2022-08-11 11:41 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-11 11:41 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +        catchError(this.handleErrorAuthorization.bind(this)),
Same about `bind`. `bind` is not bad, it was often used back in the day. Now we have a lot of language constructions that replace `bind`.

2022-08-11 11:41 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/auth.service.ts
> +        catchError(this.handleErrorAuthorization.bind(this)),
Also most developers when see `bind` think that it used for some hack

2022-08-17 03:00 UTC, panov-aleksey-saritasa requested changes

2022-08-17 03:00 UTC, panov-aleksey-saritasa commented on apps/angular/src/shared/components/header/header.component.html
> +    </ng-container>
```suggestion
    <ng-container *ngIf="(isLoggedIn$ | async) === false; else logoutLink">
      <li><a class="header__nav--link" routerLink="/login">Login</a></li>
      <li><a class="header__nav--link" routerLink="/register">Register</a></li>
    </ng-container>
    <ng-template #logoutLink>
      <li><a (click)="handleLogout($event)" class="header__nav--link header__nav--link__logout" routerLink="/">Logout</a></li>
    </ng-template>
```

2022-08-17 09:45 UTC, LocTran-saritasa commented on apps/angular/src/core/guards/is-logged-in.guard.ts
> +    return this.authService.isLoggedIn();
Yes, isLoggedIn method returns Observable<boolean>

2022-08-18 08:52 UTC, panov-aleksey-saritasa approved these changes

2022-08-18 08:52 UTC, panov-aleksey-saritasa commented on apps/angular/src/shared/components/header/header.component.css
> +}
Weird `BEM` class. I thought that you stick to `block__element--modifier` format, but actually it is not true here, consider revising your approach for class naming

2022-08-18 08:58 UTC, panov-aleksey-saritasa commented on apps/angular/src/shared/components/header/header.component.css
> +}
You could check out cool cheatsheet for BEM: https://9elements.com/bem-cheat-sheet/

2022-08-19 05:59 UTC, chernodub requested changes

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/app/features/auth/auth-routing.module.ts
> +    canActivate: [CheckIsNotLoggedInGuard],
Probably you could protect the whole module with this guard instead of applying it to each route

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/app/features/auth/auth.module.ts
> +  providers: [CheckIsLoggedInGuard, CheckIsNotLoggedInGuard],
It's not required to provide guards. You could simply make it `providedIn: 'root'`

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/app/features/auth/login/login.component.html
> +    </mat-error>
To leverage reusable error handling, consider checking out third party solutions like https://github.com/ngneat/error-tailor

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/app/features/auth/login/login.component.ts
> +    if (error instanceof HttpError) {
Your UI should never know anything about internals of repository layer (in this case, `HTTP` is a knowledge about the network layer). Otherwise, your abstraction is leaked, please check out our architecture guidelines https://wiki.saritasa.rocks/frontend/frameworks/architecture/

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/app/features/auth/register/register.component.html
> +    <mat-label class="form__field--label">Email</mat-label>
Seems like a wrong usage of BEM modifiers. Modifiers are usually a thing that "modifiers" a behavior of single element. Something like `active`/`disabled`/etc. Please consider checking out [this cheatsheet](https://9elements.com/bem-cheat-sheet/)

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/app/features/auth/register/register.component.html
> +    <input autoComplete="true"
HTML attributes are lowercased, please be careful with that :)

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/core/guards/is-logged-in.guard.ts
> +    return this.authService.isLoggedIn();
Then feel free to narrow the return type of the method :)
The narrower the types in your app -> the easier it is to maintain

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/core/guards/isProhibitedRoute.ts
> +export function isProhibitedRoute(url: URL, prohibitedUrl: string): boolean {
Prohibited usually mean that it's never accessible. Probably you meant `protected`?

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/core/guards/isProhibitedRoute.ts
> +import { environment } from '../../environments/environment';
Guards are entities provided by Angular. And I see that you've mixed this function with angular guards. This may confuse people. I think it's okay if you put this logic in `interceptors` folder since this method is used there

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/core/interceptors/auth.interceptor.ts
> +              setHeaders: { [this.authHeader]: `Bearer ${token?.accessToken}` },
I believe automatic type-narrowing here made `token` non-nullable. Probably, you can omit the optional chaining

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/core/interceptors/refresh-token-handling.interceptor.ts
> +  private readonly refreshRoute = '/api/v1/auth/token/refresh';
Seems like `/api/v1` is repetitive for every url in your app. Consider moving it in `baseUrl`

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/core/services/auth.service.ts
> +  private readonly registerApiAddress = new URL(REGISTER_URL, this.appConfig.apiUrl);
Interesting solution, but it's not consistent with other services. Consider making it the same

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/shared/components/header/header.component.css
> +  right: 0;
If you want it to stick to the top. You could use `position: sticky`. This way you won't need to set a margin for your `.default-layout`

2022-08-19 05:59 UTC, chernodub commented on apps/angular/src/shared/components/header/header.component.html
> +      <li><a (click)="handleLogout($event)" class="header__link header__link--logout" routerLink="/">Logout</a></li>
https://wiki.saritasa.rocks/frontend/languages/html#a-and-button

2022-08-19 11:29 UTC, dbitkovski requested changes

2022-08-19 11:29 UTC, dbitkovski commented on apps/angular/src/app/app-routing.module.ts
> +  },
You have two routes with the same `path` property. Not sure which one exactly angular picks but another one is unreachable.
I think you need to create 2 separate path like `auth` and `anime` and configure redirect for empty path

2022-08-19 11:29 UTC, dbitkovski commented on apps/angular/src/app/features/auth/auth-routing.module.ts
> +    canActivate: [CheckIsNotLoggedInGuard],
If I were you I wouldn't create a parent route but use the guard in `app.routing.module`. It gives you one really cool benefit, you will be able to use `canLoad` guard. Since you use lazy-loading to fetch a module, `canLoad` guard allows you to prevent download a module if it's not actually needed.
In you current implementation you always fetch a module and then check if user is allowed to open this page or not.
You can consider these guards like this:
- `canActivate` asks _If a user is allowed to reach downloaded module path?_
- `canLoad` asks _If a user is allowed to fetch a module and then go to a path?_

2022-08-19 11:29 UTC, dbitkovski commented on apps/angular/src/app/features/auth/auth.module.ts
> +    ErrorTailorModule.forRoot({
I can't say it's wrong since I haven't used this library but usually `forRoot` function is used in AppModule (which is the root of the app)

2022-08-19 11:29 UTC, dbitkovski commented on apps/angular/src/app/features/auth/login/login.component.css
> +@import "../../../../theme/authorization.css";
If you have something in common you'd better put a file within the `Auth` module to not pollute `theme` folder

2022-08-19 11:29 UTC, dbitkovski commented on apps/angular/src/app/features/auth/register/register.component.ts
> +        password: this.registerForm.value.password ?? '',
Not sure it's okay that `email` and `password` might be `null` :cat:

2022-08-19 11:29 UTC, dbitkovski commented on apps/angular/src/core/services/navigate.service.ts
> +export class NavigateService {
Honestly, I don't think it's really needed. It's totally fine to create abstractions to encapsulate some 3rd-party libraries code but angular is our foundation, there is no need to create such things.
For example, `Router.navigate` has the second parameter when we can pass query parameters. When you need it, you will have to modify your class. And this will happen every time you need another functionality on angular router.

2022-08-21 04:13 UTC, LocTran-saritasa commented on apps/angular/src/core/services/navigate.service.ts
> +export class NavigateService {
My purpose is to navigate to a specific path, for example here is the Home route. If home route is changed in the future (like from '/' to '/home') then I just need to change it in this service.
Is that reasonable? Please comment because I don't have much experience in this case.

2022-08-22 01:18 UTC, dbitkovski commented on apps/angular/src/core/services/navigate.service.ts
> +export class NavigateService {
In your case I'd prefer to have a variable that keeps home route. So you will use it like `router.navigate(homePath)`. If route path is ever change you won't need to change anything.
I think this approach is better because all you need to know is a route. You don't need some specific behavior or functionality which the class gives to you

2022-08-22 07:13 UTC, dbitkovski approved these changes

2022-08-24 04:46 UTC, chernodub approved these changes

2022-08-24 04:46 UTC, chernodub commented on apps/angular/src/app/app-routing.module.ts
> +  },
For better readability, we usually prefer putting the redirects before all routes. Just a recommendation for the future

2022-08-24 04:46 UTC, chernodub commented on apps/angular/src/app/features/auth/register/register.component.html
> +    </mat-error>
Seems like we could insert this async error into form so that error tailor could take care of this. What do you think?

2022-08-24 04:46 UTC, chernodub commented on apps/angular/src/app/features/auth/register/register.component.html
> +      autoComplete="true"
Please use lowercased autocomplete attribute everywhere. As far as I remember, this syntax is only available for jsx. Angular uses default HTML attributes. Also please revise available values for this attribute, I believe you could improve this https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

2022-09-26 02:15 UTC, closed without merging